name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm run test-npm-security
    - name: Install Dependencies
      run: npm install
    - name: Display SoftUni Username
      run: echo 'dimitar1985'
    - name: Run Unit Tests
      run: npm run test:unit
    - run: npm ci
    - run: npm run build --if-present

  User_Integration_Tests:
    runs-on: ubuntu-latest
    needs: Build_and_Test
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Run Localhost Server
      run: npm run start &
    - name: Run UI Tests
      run: npm run test:ui
    - run: npm ci
    - run: npm run build --if-present

  Deploy_Application:    
    runs-on: ubuntu-latest
    needs: User_Integration_Tests
    steps:
      - name: Deploy to production
        uses: sws2apps/render-deployment@main
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}
